### ISSUE TITLE
How to create a custom ProviderManager

### ISSUE THREAD

**Issue by idavollen** [eugenp/learn-spring-security#27]
Hei Eugen,

I read your nice blogs concerning Spring Security from baeldung.com.  I'd like to consult you with one question, creating my custom Provider Manager.

In my Spring Boot application, I've come out my custom MyProviderManager where I'd like to control the logic inside method authenticate

```
public Authentication authenticate(Authentication authentication) {
     // instead of iterating in the AuthenticationProvider list one by one
     // I'd rather choose the right AuthenticationProvider based on the currently requested URL path
     RequestDetails requestDetails = authentication.getDetails();
     if ("/ad/sso".equals(requestDetails.getPath())) {
         return adAuthenticationProvider.authenticate(authentication);
     } else if ("/saml/sso".equals(requestDetails.getPath())) {
         return samlAuthenticationProvider.authenticate(authentication);
     } else if ("/oidc/sso".equals(requestDetails.getPath())) {
         return oidcAuthenticationProvider.authenticate(authentication);
     } else  {
         return ldapAuthenticationProvider.authenticate(authentication);
     }
     return null;
 }
```
However, I'm now having it hard to inject my custom `MyProviderManager` with `AuthenticationManagerBuilder` so that the method `performBuild()` in _AuthenticationManagerBuilder_ will return _MyProviderManager_ instead of the default one from Spring Security

I had even tried to come out my custom `MyAuthenticationManagerBuilder exends AuthenticationManagerBuilder `and overridden `performBuild`() method, but I faced the same issue of how to inject my custom `AuthenticationManagerBuilder` to Spring Boot

It is really appreciate if you could shed the light on the issues here or have better alternative ideas tackling my special requirements

**Comment by lor6** [comment]
Hi @idavollen 

I'm not sure if it's possible to override the authentication manager itself. 

But you can create a custom AuthenticationProvider which verifies the path and then delegates further to the right class based on it. Then only wire this delegating Provider into your main security configuration.

Another option is to create 2 separate security configuration for each of the paths you have; you can find an example of this here: https://www.baeldung.com/spring-security-two-login-pages

I'll close this issue since it's not a problem with this repository.

**Comment by LucianoTerziotti** [comment]
Hi! I am trying to create a CustomAuthenticationProvider who resolves the authenticate method chosing if a token is valid or not. I dont use a normal user and pass for authenticate, it is just a token to authenticate a third app. Do you know how can i acomplish that? I am seraching everywhere and couldn't find anything like i need. 
Thanks very much!
