### ISSUE TITLE
No Role, Privilege implementation

### ISSUE THREAD

**Issue by manojsharma20** [eugenp/learn-spring-security#4]
I did not found Role Privilege implementation found in m9-l3, There is only Role based ACL not Role Permission based ACL.

**Comment by eugenp** [comment]
Hey @manojsharma20  - that sounds like an interesting point - I'm not sure I fully understand. 
That lesson is about secure method invocation. What does that have to do with ACL - and what is the inconsistency you're seeing in the codebase?
Cheers, 
Eugen.

**Comment by manojsharma20** [comment]
Hi @eugenp , I have studied your both lesson 2 part-1 and part-2 about "The Topology of Roles and Privileges". You have mentioned the role and permission implementation in the videos and also in the note you have mentioned the start point and complete solution which is module9 lesson 1 and module 9 lession 3. But your module 9 lesson three does not contain complete implementation as your video contains and showing.

**Comment by eugenp** [comment]
Hey @manojsharma20 - I checked and you're right, the implementation is missing from L3. It's on the TODO list of the team to sort out - thanks for letting me know. 
Cheers, 
Eugen.

**Comment by krnbr** [comment]
@eugenp , I think we may close this now?

**Comment by Androidniraj** [comment]
What is the password encoder method in above program
